<script>
    window.translations = {
        show: "{{ __('backend.Show') }}",
        entries: "{{ __('backend.entries') }}",
        Search: "{{ __('backend.Search:') }}",
        Showing: "{{ __('backend.Showing') }}",
        NoData: "{{ __('backend.No data available in table') }}",
        to: "{{ __('backend.to') }}",
        nameOfItem: "{{ __('backend.name of Item') }}",
        of: "{{ __('backend.of') }}",
        noRecord: "{{ __('backend.No matching records found') }}",
        deletemodal1: "{{ __('backend.Are you sure ?') }}",
        deletemodal2: "{{ __('backend.You wont be able to revert this!') }}",
        cancle: "{{ __('backend.Cancel') }}",
        confirm: "{{ __('backend.confirm') }}",
        deleted: "{{ __('backend.Deleted!') }}",
        success: "{{ __('backend.file has been deleted successfully.') }}",
        continue: "{{ __('backend.continue') }}",
        nameOfProject: "{{ __('backend.name of project') }}",
        description: "{{ __('backend.description') }}",
        startingFrom: "{{ __('backend.Starting From') }}",
        endingIn: "{{ __('backend.Ending In') }}",
        email: "{{ __('backend.email') }}",
        projectDetails: "{{ __('backend.Project details') }}",

    };
    window.translation = {
        deletemodal1: "{{ __('backend.Are you sure ?') }}",
        deletemodal2: "{{ __('backend.You wont be able to revert this!') }}",
        cancle: "{{ __('backend.Cancel') }}",
        confirm: "{{ __('backend.confirm') }}",
        deleted: "{{ __('backend.Deleted!') }}",
        success: "{{ __('backend.file has been deleted successfully.') }}",
        continue: "{{ __('backend.continue') }}",
        userInfo: "{{ __('backend.userInfo') }}",
        email: "{{ __('backend.email') }}",
        userName: "{{ __('backend.name') }}",
        phone: "{{ __('backend.phone') }}",
        UserType: "{{ __('backend.UserType') }}",
        nameactivities: "{{ __('backend.name of activities') }}",
        save: "{{ __('backend.save') }}",
        QuotesDetails: "{{ __('backend.QuotesDetails') }}",
        Accepttheoffer: "{{ __('backend.Accept the offer') }}",
        offerrejected: "{{ __('backend.offer rejected') }}",
        Refundetails: "{{ __('backend.Refund request details') }}",
        amount: "{{ __('backend.the amount') }}",
        beneficiary: "{{ __('backend.beneficiary') }}",
        Createdat: "{{ __('backend.Created at') }}",
        Membership: "{{ __('backend.Membership No') }}",
        IBAN: "{{ __('backend.Account number IBAN') }}",
        Download: "{{ __('backend.Download the attached image') }}",
        sendComment: "{{ __('frontend.sendComment') }}",
        attach: "{{ __('backend.attach a picture') }}",
        Typemessage: "{{ __('backend.Type a message..') }}",
        Contractdetails: "{{ __('backend.Contract details') }}",
        ContractID: "{{ __('backend.contract number') }}",
        typeCompany: "{{ __('backend.company type') }}",
        CommercialRecord: "{{ __('backend.Commercial record') }}",
        company_name: "{{ __('backend.name of company') }}",
        BriefDescription: "{{ __('backend.Brief description') }}",
        City: "{{ __('backend.city') }}",
        renewable: "{{ __('backend.renewable') }}",
        fbatch: "{{ __('backend.The first batch') }}",
        sbatch: "{{ __('backend.second batch') }}",
        tbatch: "{{ __('backend.third batch') }}",
        finalBatch: "{{ __('backend.final batch') }}",
        Datecontract: "{{ __('backend.Date of contract') }}",
        sDatecontract: "{{ __('backend.Contract start date') }}",
        eDatecontract: "{{ __('backend.Contract end date') }}",
        Attachedcontract: "{{ __('backend.Attached contract file') }}",
        downloadcontact: "{{ __('backend.Download the attached contract file') }}",
        Invoices: "{{ __('backend.Invoices') }}",
        product: "{{ __('backend.product or service') }}",
        Fixed: "{{ __('backend.Fixed value') }}",
        Tax: "{{ __('backend.Tax') }}",
        percent: "{{ __('backend.percent') }}",
        DiscountType: "{{ __('backend.Discount type') }}",
        Price: "{{ __('backend.Price') }}",
        Quantity: "{{ __('backend.Quantity') }}",
        nameService: "{{ __('backend.name of Service') }}",
        Discount: "{{ __('backend.Discount') }}",
        invoiceNumber: "{{ __('backend.invoice number') }}",
        customerName: "{{ __('backend.customer name') }}",
        responsible: "{{ __('backend.responsible') }}",
        InvoiceDate: "{{ __('backend.Invoice date') }}",
        InvoiceDetails: "{{ __('backend.Invoice details') }}",
        addInvoice: "{{ __('backend.add invoice') }}",
        close: "{{ __('backend.close') }}",
        bankDetails: "{{ __('backend.Bank details') }}",
        BankName: "{{ __('backend.Bank name') }}",
        accountName: "{{ __('backend.account name') }}",
        accountNumber: "{{ __('backend.account number') }}",
        IBANumber: "{{ __('backend.IBAN') }}",
        ContractApproval: "{{ __('backend.Contract approval') }}",
        contractRefusal: "{{ __('backend.contract refusal') }}",
        systemMessages: "{{ __('backend.system messages') }}",
        AttachedRequired: "{{ __('backend.Attached contract file is required') }}",
        AllRequired: "{{ __('backend.All fields are required') }}",
        batch4: "{{ __('backend.batch4') }}",
        batch5: "{{ __('backend.batch5') }}",
        batch6: "{{ __('backend.batch6') }}",
        batch7: "{{ __('backend.batch7') }}",
        batch8: "{{ __('backend.batch8') }}",
        batch9: "{{ __('backend.batch9') }}",
        batch10: "{{ __('backend.batch10') }}",
        ContractStatus: "{{ __('backend.Contract Status') }}",
        PaymentSystem: "{{ __('backend.Payment system') }}",
        ContactUpdatedSuccessfully: "{{ __('backend.Contact Updated Successfully') }}",
        CaseCreatedSuccessfully: "{{ __('backend.Case created successfully') }}",
        Message: "{{ __('backend.Message text') }}",
        Editmessage: "{{ __('backend.Edit message') }}",
        TheAttachedPhoto: "{{ __('backend.The attached photo') }}",
        Mins: "{{ __('backend.Mins') }}",
        Secs: "{{ __('backend.Secs') }}",
        Hours: "{{ __('backend.Hours') }}",
        Days: "{{ __('backend.Days') }}",
        Atleast: "{{ __('backend.At least one bank must be selected') }}",
        Clickimage: "{{ __('backend.Click here to download or drop the image') }}",
        verification: "{{ __('backend.verification') }}",
        Customerrequired: "{{ __('backend.Customer name is required') }}",
        customername: "{{ __('backend.customer name') }}",
        address: "{{ __('backend.address') }}",
        Addressrequired: " {{ __('backend.Address is required') }}",
        TaxNumber: "{{ __('backend.Tax Number') }}",
        Taxrequired: "{{ __('backend.Tax number is required') }}",
        Responsiblerequired: "{{ __('backend.Responsible Name Required') }}",
        Mobilerequired: "{{ __('backend.Mobile number is required') }}",
        Emailrequired: "{{ __('backend.Email is required') }}",
        ThecompanyRevenue: "{{ __('backend.The company revenue') }}",
        fstatus: "{{ __('backend.status') }}",
        active: "{{ __('backend.active') }}",
        Inactive: "{{ __('backend.in active') }}",
        TicketCreatedSuccessfully: "{{ __('backend.Ticket created successfully') }}",
        employment:"{{ __('backend.employment') }}",
        on_warranty:"{{ __('backend.on warranty') }}",
        rent_contract:"{{ __('backend.rent contract') }}",
        Bank_guarantee:"{{ __('backend.Bank guarantee') }}",
        The_required_paperwork:"{{ __('backend.The required paperwork') }}",
        nots:"{{ __('backend.nots') }}",
        Application_conditions:"{{ __('backend.Application conditions') }}",
        Previous:"{{__('backend.Previous')}}",
        Next:"{{__('backend.Next')}}",
        ProjectvalueRequired:"{{__('backend.Project value required')}}",
        ProjectTitleRequired:"{{__('backend.Project title is required')}}",
        MainActivityRequired:"{{__('backend.Main activity required')}}",
        AdditionalActivitRequired:"{{__('backend.Additional activity is required')}}",
        ShortDescriptionRequired:"{{__('backend.Short description required')}}",
        ApplicationDeadlineIsRequired:"{{__('backend.Application deadline is required')}}",
        neighborhoodIsRequired:"{{__('backend.neighborhood is required')}}",
        ClassificationCategoryRequired:"{{__('backend.Classification category required')}}",
        ServicesProvided:"{{__('backend.Services provided')}}",
        send:"{{__('backend.send')}}",
        ReceivingOrders:"{{__('backend.Receiving orders')}}",
        Individuals:"{{__('backend.Individuals')}}",
        Institutions:"{{__('backend.Institutions')}}",
        Both:"{{__('backend.Both')}}",
        waitingForAcceptance:"{{__('backend.waiting for acceptance')}}",
        OrderDetails:"{{__('backend.Order details')}}",
        RequestAccept:"{{__('backend.Request Accept')}}",
        RejectionApplication:"{{__('backend.Rejection of the application')}}",
        uploadRecipt:"{{__('backend.uploadRecipt')}}",
        AwaitingPayment:"{{__('backend.Awaiting payment')}}",
        sendPrice:"{{__('backend.send new price')}}",
    };
</script>